'use strict';
const Layout = require('../layouts/default.jsx');
const React = require('react');


class AboutPage extends React.Component {
    render() {

        return (
            <Layout
                title="About us"
                activeTab="about">

                <div className="row">
                    <div className="col-sm-12">
                        <h1 className="page-header">About Interra Data</h1>
                        <div className="media">
                            <div className="media-body">
                                <p>
                                    Interra Data is an Open Data Catalog powered by static JSON files. Using static files as the metadata store makes publishing and updating data easier and more efficient.
                                </p>
                                <p>
                                    Interra Data is similar to JKAN. The main conceptual difference is it is created to run as a service that is not coupled to Github Pages.
                                </p>
                                <p>
                                  Interra Data consists of two major decoupled components.
                                  <ul>
                                      <li key="1"><strong>Data Admin</strong> which allows non-technical users to sign-up and create and manage a catalog. Data generated by Data Admin is stored in JSON files.</li>
                                      <li key="2"><strong>Data Generate</strong> which generates a data catalog from JSON files.</li>
                                  </ul>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </Layout>
        );
    }
}


module.exports = AboutPage;
