'use strict';
const FluxConstant = require('flux-constant');


module.exports = FluxConstant.set([
    'DELETE',
    'DELETE_RESPONSE',
    'DELETE_CONTENT',
    'DELETE_CONTENT_RESPONSE',
    'GET_COLLECTION_SCHEMA',
    'GET_COLLECTION_SCHEMA_RESPONSE',
    'GET_USER',
    'GET_USER_RESPONSE',
    'GET_SITE',
    'GET_SITE_RESPONSE',
    'GET_CONTENT',
    'GET_CONTENT_RESPONSE',
    'GET_DATASETS',
    'GET_DATASETS_RESPONSE',
    'SAVE_DATASET',
    'SAVE_DATASET_RESPONSE',
    'UPDATE_FORM_DATA',
    'UPDATE_DATASET',
    'UPDATE_DATASET_RESPONSE',
    'HIDE_DATASET_SAVE_SUCCESS'
]);
